1640227487.508752｜[DEBUG] [__main__] Starting up...
1640227765.505318｜[DEBUG] [__main__] Starting up...
1640227905.135265｜[DEBUG] [__main__] Starting up...
1640227963.561103｜[DEBUG] [__main__] Starting up...
1640228012.590535｜[DEBUG] [__main__] Starting up...
1640228015.220192｜[INFO] [takt.on_ready] Saiki is ready
1640228027.208391｜[DEBUG] [__main__] Starting up...
1640228029.826157｜[INFO] [takt.on_ready] Takt is ready
1640228144.388709｜[DEBUG] [__main__] Starting up...
1640228147.000168｜[INFO] [takt.on_ready] Takt is ready
1640228184.096864｜[DEBUG] [__main__] Starting up...
1640228186.75232｜[INFO] [takt.on_ready] Takt is ready
1640228191.488019｜[ERROR] [error.error_handler] An unknown error occured: AttributeError 'NoneType' object has no attribute 'stop'
1640228377.625428｜[DEBUG] [__main__] Starting up...
1640228380.262292｜[INFO] [takt.on_ready] Takt is ready
1640228384.131218｜[ERROR] [error.error_handler] An unknown error occured: RuntimeError PyNaCl library needed in order to use voice
1640228559.043179｜[DEBUG] [__main__] Starting up...
1640228561.684944｜[INFO] [takt.on_ready] Takt is ready
1640228576.080789｜[ERROR] [error.error_handler] An unknown error occured: TypeError expected str, bytes or os.PathLike object, not dict
1640228624.21999｜[DEBUG] [__main__] Starting up...
1640228626.832654｜[INFO] [takt.on_ready] Takt is ready
1640228636.693718｜[ERROR] [error.error_handler] An unknown error occured: TypeError string indices must be integers
1640228659.14154｜[DEBUG] [__main__] Starting up...
1640228661.727052｜[INFO] [takt.on_ready] Takt is ready
